title: Marti Figueres
logo: "images/25LEHIGH-00353-2-1010677197-1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/marti-figueres/">LinkedIn</a> 
  <br>
  <a href="pdf/Figueres_Marti Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/martifigueres/">GitHub</a>  

theme: jekyll-theme-minimal
