title: Marti Figueres
logo: "https://github.com/martifigueres/martifigueres.github.io/blob/master/images/IBE%20Headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/marti-figueres/">LinkedIn</a> 
  <br>
  <a href="pdf/Figueres_Marti Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/martifigueres/">GitHub</a>  

theme: jekyll-theme-minimal
